### ISSUE TITLE
How to produce MSR Video Description Corpus_refine.csv

### ISSUE THREAD

**Issue by CHENGY12** [Yugnaynehc/banet#1]
Hello, I wonder how you refine the corpus of youtubeclips. Could you please provide the file or tell me the exact places you modified?

**Comment by Yugnaynehc** [comment]
Hi! You can download the original "MSR Video Description Corpus.csv" from https://www.microsoft.com/en-us/download/details.aspx?id=52422. As for "MSR Video Description Corpus_refine.csv", I just removed some dirty data and you can do it yourself. Due to licensing limitations, I can not share you with the csv file. Sorry about that.
